apiVersion: apps/v1
kind: Deployment
metadata:
  name: event-service
  namespace: school-platform
spec:
  replicas: 1
  selector:
    matchLabels:
      app: event-service
  template:
    metadata:
      labels:
        app: event-service
    spec:
      containers:
      - name: event-service
        image: ${DOCKER_HUB_USER}/event-service:latest
        ports:
        - containerPort: 8081
        env:
        - name: SPRING_DATASOURCE_URL
          value: "jdbc:mysql://host.docker.internal:3306/event_service_db?createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true&useSSL=false"
        - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
          value: "http://host.docker.internal:8761/eureka/"
        - name: ML_SERVICE_URL
          value: "http://ml-service:5000"
        resources:
          requests:
            cpu: "200m"
            memory: "256Mi"
          limits:
            cpu: "500m"
            memory: "512Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: event-service
  namespace: school-platform
spec:
  selector:
    app: event-service
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081
  type: ClusterIP
